<?php
$document = $document ?? null;
if (!$document) {
    echo '<p class="receipt-subtitle">Document not found.</p>';
    return;
}

$content = ClinicalDocument::decodeContent($document);
$documentNo = (string) ($document['document_no'] ?? '');
$issuedAt = (string) ($document['issued_at'] ?? '');
$issuedLabel = $issuedAt !== '' ? format_datetime($issuedAt) : '';
$visitDate = format_appt_date($content['consultation_date'] ?? date('Y-m-d'));
$doctorName = trim((string) ($content['doctor_name'] ?? ''));
$issuedBy = trim((string) ($content['issued_by_name'] ?? $document['issued_by_display_name'] ?? $document['issued_by_username'] ?? 'Staff'));
$purpose = trim((string) ($content['purpose'] ?? ''));
$restDays = $content['rest_days'] ?? null;
$remarks = trim((string) ($content['remarks'] ?? ''));
$clinicalNotes = trim((string) ($content['clinical_notes'] ?? ''));

$basePath = app_base_path();
$logoPath = '/assets/bhs_logo_v3.png';
$uLogo = ($basePath === '' ? '' : $basePath) . $logoPath;
$root = defined('BHC_ROOT') ? BHC_ROOT : dirname(__DIR__, 2);
$hasLogo = is_file($root . '/public' . $logoPath) || is_file($root . $logoPath);
?>

<article class="receipt-sheet">
  <header class="receipt-header">
    <?php if ($hasLogo): ?>
      <img class="receipt-logo" src="<?= h($uLogo) ?>" alt="BHC Logo" />
    <?php endif; ?>
    <div class="receipt-org">Barangay Health Center</div>
    <div class="receipt-subtitle">Brgy. Balong Bato, San Juan City</div>
    <div class="receipt-doc-title"><?= h((string) ($document['title'] ?? 'Medical certificate')) ?></div>
    <div class="receipt-subtitle" style="margin-top: 8px;">
      Document no. <strong><?= h($documentNo) ?></strong>
    </div>
  </header>

  <table class="receipt-meta">
    <colgroup>
      <col class="col-label" />
      <col class="col-value" />
    </colgroup>
    <tr>
      <td>Patient name</td>
      <td><strong><?= h($content['full_name'] ?? '') ?></strong></td>
    </tr>
    <tr>
      <td>BHC ID</td>
      <td><?= h($content['bhc_id'] ?? '') ?></td>
    </tr>
    <tr>
      <td>Visit date</td>
      <td><?= h($visitDate) ?></td>
    </tr>
    <tr>
      <td>Issued on</td>
      <td><?= h($issuedLabel) ?></td>
    </tr>
    <tr>
      <td>Diagnosis</td>
      <td><?= h($content['diagnosis'] ?? '—') ?></td>
    </tr>
    <?php if ($doctorName !== ''): ?>
      <tr>
        <td>Attending doctor</td>
        <td><?= h($doctorName) ?></td>
      </tr>
    <?php endif; ?>
  </table>

  <div class="receipt-section-title">Certificate details</div>
  <table class="receipt-meta">
    <colgroup>
      <col class="col-label" />
      <col class="col-value" />
    </colgroup>
    <tr>
      <td>Purpose</td>
      <td><strong><?= h($purpose) ?></strong></td>
    </tr>
    <?php if ($restDays !== null && $restDays !== ''): ?>
      <tr>
        <td>Recommended rest</td>
        <td><?= h((string) $restDays) ?> day<?= (int) $restDays === 1 ? '' : 's' ?></td>
      </tr>
    <?php endif; ?>
    <?php if ($clinicalNotes !== ''): ?>
      <tr>
        <td>Clinical notes</td>
        <td><?= nl2br(h($clinicalNotes)) ?></td>
      </tr>
    <?php endif; ?>
    <?php if ($remarks !== ''): ?>
      <tr>
        <td>Remarks</td>
        <td><?= nl2br(h($remarks)) ?></td>
      </tr>
    <?php endif; ?>
  </table>

  <p style="margin: 18px 0 0; line-height: 1.6; font-size: 14px;">
    This is to certify that the patient named above was examined at this barangay health center
    on <strong><?= h($visitDate) ?></strong> and the findings above are true and correct to the best of my knowledge.
  </p>

  <?php
    $patientSignatureLabel = 'Patient signature';
    require __DIR__ . '/../partials/clinical_document_signatures.php';
  ?>

  <p class="receipt-footnote">
    This document is generated by the <?= h(app_name()) ?>.
    Saved clinical document — reprint anytime from patient history.
  </p>
</article>
