<?php
$document = $document ?? null;
if (!$document) {
    echo '<p class="receipt-subtitle">Document not found.</p>';
    return;
}

$content = ClinicalDocument::decodeContent($document);
$documentNo = (string) ($document['document_no'] ?? '');
$issuedAt = (string) ($document['issued_at'] ?? '');
$issuedLabel = $issuedAt !== '' ? format_datetime($issuedAt) : '';
$visitDate = format_appt_date($content['consultation_date'] ?? date('Y-m-d'));
$doctorName = trim((string) ($content['doctor_name'] ?? ''));
$issuedBy = trim((string) ($content['issued_by_name'] ?? $document['issued_by_display_name'] ?? $document['issued_by_username'] ?? 'Staff'));
$referredTo = trim((string) ($content['referred_to'] ?? ''));
$reason = trim((string) ($content['reason'] ?? ''));
$clinicalSummary = trim((string) ($content['clinical_summary'] ?? $content['diagnosis'] ?? ''));

$basePath = app_base_path();
$logoPath = '/assets/bhs_logo_v3.png';
$uLogo = ($basePath === '' ? '' : $basePath) . $logoPath;
$root = defined('BHC_ROOT') ? BHC_ROOT : dirname(__DIR__, 2);
$hasLogo = is_file($root . '/public' . $logoPath) || is_file($root . $logoPath);
?>

<article class="receipt-sheet">
  <header class="receipt-header">
    <?php if ($hasLogo): ?>
      <img class="receipt-logo" src="<?= h($uLogo) ?>" alt="BHC Logo" />
    <?php endif; ?>
    <div class="receipt-org">Barangay Health Center</div>
    <div class="receipt-subtitle">Brgy. Balong Bato, San Juan City</div>
    <div class="receipt-doc-title"><?= h((string) ($document['title'] ?? 'Referral letter')) ?></div>
    <div class="receipt-subtitle" style="margin-top: 8px;">
      Document no. <strong><?= h($documentNo) ?></strong>
    </div>
  </header>

  <table class="receipt-meta">
    <colgroup>
      <col class="col-label" />
      <col class="col-value" />
    </colgroup>
    <tr>
      <td>Patient name</td>
      <td><strong><?= h($content['full_name'] ?? '') ?></strong></td>
    </tr>
    <tr>
      <td>BHC ID</td>
      <td><?= h($content['bhc_id'] ?? '') ?></td>
    </tr>
    <tr>
      <td>Visit date</td>
      <td><?= h($visitDate) ?></td>
    </tr>
    <tr>
      <td>Issued on</td>
      <td><?= h($issuedLabel) ?></td>
    </tr>
    <?php if ($doctorName !== ''): ?>
      <tr>
        <td>Referring doctor</td>
        <td><?= h($doctorName) ?></td>
      </tr>
    <?php endif; ?>
  </table>

  <div class="receipt-section-title">Referral details</div>
  <table class="receipt-meta">
    <colgroup>
      <col class="col-label" />
      <col class="col-value" />
    </colgroup>
    <tr>
      <td>Referred to</td>
      <td><strong><?= h($referredTo) ?></strong></td>
    </tr>
    <tr>
      <td>Reason for referral</td>
      <td><?= nl2br(h($reason)) ?></td>
    </tr>
    <tr>
      <td>Clinical summary</td>
      <td><?= nl2br(h($clinicalSummary)) ?></td>
    </tr>
  </table>

  <p style="margin: 18px 0 0; line-height: 1.6; font-size: 14px;">
    Please accept this patient for further evaluation and management. Thank you for your cooperation.
  </p>

  <?php
    $patientSignatureLabel = 'Patient / guardian signature';
    require __DIR__ . '/../partials/clinical_document_signatures.php';
  ?>

  <p class="receipt-footnote">
    This document is generated by the <?= h(app_name()) ?>.
    Saved clinical document — reprint anytime from patient history.
  </p>
</article>
